// GENERATED by odb_mkecofixture — do not edit.
// The matching eco_demo.odb is emitted from the same statements, so instance,
// pin and cell names are identical on both sides of the ECO loop by construction.
//
// Two-flop ring: r1.Q -> g1(INV) -> r2.D, and r2.Q (= port y) -> r1.D. Both flop D
// pins are launched by a flop Q, so hold is register-to-register and repairable.
module eco_demo ( clk, y );
  input  clk;
  output y;
  wire q1, n1;
  DFF r1 ( .CK(clk), .D(y), .Q(q1) );
  INV g1 ( .A(q1), .Y(n1) );
  DFF r2 ( .CK(clk), .D(n1), .Q(y) );
endmodule
